window.PORTFOLIO_PROJECTS = [
  {
    slug: "al-qibla-air-services",
    name: "Al Qibla Air Services",
    repo: "al-qibla-air-services",
    description: "Premium travel agency website and admin-managed platform for Umrah packages, worldwide ticketing, tours, visas, reviews, inquiries, WhatsApp booking, and animated travel UI.",
    category: "web",
    tags: ["Next.js", "TypeScript", "Supabase", "Travel"],
    url: "https://github.com/mafzalkalwardev/al-qibla-air-services",
    image: "assets/projects/al-qibla-air-services.svg",
    featured: true
  },
  {
    slug: "tony-ai",
    name: "Tony AI",
    repo: "tony-ai",
    description: "Local voice-first Windows laptop assistant built with Python and PyQt6 for voice commands, wake mode, safety approvals, Git/project tools, and local automation.",
    category: "ml",
    tags: ["Python", "PyQt6", "Voice AI", "Windows"],
    url: "https://github.com/mafzalkalwardev/tony-ai",
    image: "assets/projects/tony-ai.svg",
    featured: true
  },
  {
    slug: "sms-marketing-crm",
    name: "SMS Marketing CRM",
    repo: "sms-marketing-crm",
    description: "Compliant SMS CRM and marketing dashboard with Vonage API integration for contact management, campaigns, consent-aware messaging, and analytics.",
    category: "web",
    tags: ["CRM", "Vonage", "SMS", "Dashboard"],
    url: "https://github.com/mafzalkalwardev/sms-marketing-crm",
    image: "assets/projects/sms-marketing-crm.svg",
    featured: true
  },
  {
    slug: "indus-transport-auto-dialer",
    name: "Indus Transport Auto Dialer",
    repo: "indus-transport-auto-dialer",
    description: "Production Windows auto dialer for dispatch teams with Google Voice browser automation, Excel campaign import, resume-safe calling, local logs, and PyQt6 desktop UI.",
    category: "desktop",
    tags: ["Python", "PyQt6", "Google Voice", "Auto Dialer"],
    url: "https://github.com/mafzalkalwardev/indus-transport-auto-dialer",
    image: "assets/projects/indus-transport-auto-dialer.png",
    featured: true
  },
  {
    slug: "bulk-email-verifier",
    name: "Bulk Email Verifier",
    repo: "bulk-email-verifier",
    description: "Self-hosted bulk email verification platform with syntax, MX, SMTP mailbox checks, Node.js UI, Go verification services, and Docker deployment.",
    category: "email",
    tags: ["Go", "Node.js", "SMTP", "Docker"],
    url: "https://github.com/mafzalkalwardev/bulk-email-verifier",
    image: "assets/projects/bulk-email-verifier.png",
    featured: true,
    video: "assets/videos/bulk-email-verifier.webm"
  },
  {
    slug: "fiverr-lead-extractor-crm",
    name: "Fiverr Lead Extractor CRM",
    repo: "fiverr-lead-extractor-crm",
    description: "Full-stack lead extraction CRM for Fiverr review research with Playwright workers, MongoDB, BullMQ queues, Excel export, admin dashboard, and Electron desktop packaging.",
    category: "web",
    tags: ["TypeScript", "Playwright", "MongoDB", "Electron"],
    url: "https://github.com/mafzalkalwardev/fiverr-lead-extractor-crm",
    image: "assets/projects/fiverr-lead-extractor-crm.png",
    featured: true
  },
  {
    slug: "callaudit-x",
    name: "CallAudit-X",
    repo: "CallAudit-X",
    description: "AI call auditing SaaS for transcription, quality scoring, review workflows, analytics dashboards, and call-center performance insights.",
    category: "ml",
    tags: ["AI", "TypeScript", "SaaS", "Analytics"],
    url: "https://github.com/mafzalkalwardev/CallAudit-X",
    image: "assets/projects/callaudit-x.png",
    featured: true,
    video: "assets/videos/callaudit-x.webm"
  },
  {
    slug: "google-voice-call-state-detector",
    name: "Google Voice Call State Detector",
    repo: "google-voice-call-state-detector",
    description: "Manifest V3 Google Voice call state detector with live tab-audio metrics, Deepgram transcription, voicemail detection, and call-screening heuristics.",
    category: "automation",
    tags: ["Google Voice", "Chrome Extension", "Deepgram", "Audio"],
    url: "https://github.com/mafzalkalwardev/google-voice-call-state-detector",
    image: "assets/projects/google-voice-call-state-detector.svg",
    featured: true
  },
  {
    slug: "google-voice-dispatch-agent",
    name: "Google Voice Dispatch Agent",
    repo: "google-voice-dispatch-agent",
    description: "Selenium-based Google Voice dispatch assistant with Groq-generated call scripts, local TTS, voicemail handling, and low-cost outbound workflow automation.",
    category: "automation",
    tags: ["Python", "Selenium", "Groq", "Voice"],
    url: "https://github.com/mafzalkalwardev/google-voice-dispatch-agent",
    image: "assets/projects/google-voice-dispatch-agent.png",
    featured: true,
    video: "assets/videos/google-voice-dispatch-agent.webm"
  },
  {
    slug: "playwright-website-scraper-pro",
    name: "Playwright Website Scraper Pro",
    repo: "playwright-website-scraper-pro",
    description: "Advanced website scraping and cloning toolkit with Playwright automation, desktop GUI, Express backend, screenshots, asset downloading, and multi-page export.",
    category: "scraper",
    tags: ["Playwright", "Node.js", "Express", "Automation"],
    url: "https://github.com/mafzalkalwardev/playwright-website-scraper-pro",
    image: "assets/projects/playwright-website-scraper-pro.png",
    featured: true,
    video: "assets/videos/playwright-website-scraper-pro.webm"
  },
  {
    slug: "mailforge",
    name: "MailForge",
    repo: "mailforge",
    description: "Self-hosted email operations platform for list verification, multi-sender outreach campaigns, reply management, and private email workflow automation.",
    category: "email",
    tags: ["Go", "SMTP", "Campaigns", "Self-hosted"],
    url: "https://github.com/mafzalkalwardev/mailforge",
    image: "assets/projects/mailforge.png",
    featured: false
  },
  {
    slug: "email-verifier-pro",
    name: "Email Verifier Pro",
    repo: "email-verifier-pro",
    description: "Full-stack email verification web app with Node.js, Express, MongoDB, JWT authentication, bulk CSV/XLSX validation, dashboard analytics, and validation history.",
    category: "email",
    tags: ["Node.js", "Express", "MongoDB", "JWT"],
    url: "https://github.com/mafzalkalwardev/email-verifier-pro",
    image: "assets/projects/email-verifier-pro.png",
    featured: false
  },
  {
    slug: "email-verification-platform",
    name: "Email Verification Platform",
    repo: "email-verification-platform",
    description: "Full-stack email verification platform with authentication, bulk CSV/XLSX uploads, MongoDB history tracking, analytics, and EmailListVerify API integration.",
    category: "email",
    tags: ["Node.js", "MongoDB", "CSV", "API"],
    url: "https://github.com/mafzalkalwardev/email-verification-platform",
    image: "assets/projects/email-verification-platform.png",
    featured: false
  },
  {
    slug: "python-auto-dialer-pro",
    name: "Python Auto Dialer Pro",
    repo: "python-auto-dialer-pro",
    description: "Python GUI auto dialer with Excel contact loading, automated dial pad control, call logging, resume support, hotkeys, and PyAutoGUI desktop automation.",
    category: "desktop",
    tags: ["Python", "PyAutoGUI", "Excel", "Dialer"],
    url: "https://github.com/mafzalkalwardev/python-auto-dialer-pro",
    image: "assets/projects/python-auto-dialer-pro.png",
    featured: false
  },
  {
    slug: "excel-call-queue-automator",
    name: "Excel Call Queue Automator",
    repo: "excel-call-queue-automator",
    description: "Desktop Python call queue tool that imports Excel phone lists, controls a dial pad by screen coordinates, supports hotkeys, resumes calls, and exports CSV logs.",
    category: "desktop",
    tags: ["Python", "Excel", "CSV", "Automation"],
    url: "https://github.com/mafzalkalwardev/excel-call-queue-automator",
    image: "assets/projects/excel-call-queue-automator.png",
    featured: false
  },
  {
    slug: "fmcsa-safer-scraper",
    name: "FMCSA SAFER Scraper",
    repo: "fmcsa-safer-scraper",
    description: "Python Selenium scraper for extracting carrier and MC data from FMCSA SAFER, including company details, phone numbers, addresses, and emails.",
    category: "scraper",
    tags: ["Python", "Selenium", "FMCSA", "Logistics"],
    url: "https://github.com/mafzalkalwardev/fmcsa-safer-scraper",
    image: "assets/projects/fmcsa-safer-scraper.png",
    featured: false
  },
  {
    slug: "safer-carrier-extractor",
    name: "SAFER Carrier Extractor",
    repo: "safer-carrier-extractor",
    description: "Python carrier data extractor for FMCSA SAFER records, legal names, addresses, phone numbers, emails, and logistics prospecting workflows.",
    category: "scraper",
    tags: ["Python", "Selenium", "Carrier Data", "Logistics"],
    url: "https://github.com/mafzalkalwardev/safer-carrier-extractor",
    image: "assets/projects/safer-carrier-extractor.png",
    featured: false
  },
  {
    slug: "safer-web-scraper",
    name: "SAFER Web Scraper",
    repo: "safer-web-scraper",
    description: "Python web scraping toolkit for extracting carrier and logistics data from FMCSA SAFER systems using Selenium and notebook-driven workflows.",
    category: "scraper",
    tags: ["Python", "Selenium", "Jupyter", "Data"],
    url: "https://github.com/mafzalkalwardev/safer-web-scraper",
    image: "assets/projects/safer-web-scraper.png",
    featured: false
  },
  {
    slug: "canadian-website-scraper",
    name: "Canadian Website Scraper",
    repo: "Canadian-Website-Scraper",
    description: "Playwright scraper for rebuilding Canadian study website content, including protected audio, text, MCQs, pictures, and offline replica assets.",
    category: "scraper",
    tags: ["Playwright", "JavaScript", "Scraper", "Replica"],
    url: "https://github.com/mafzalkalwardev/Canadian-Website-Scraper",
    image: "assets/projects/canadian-website-scraper.png",
    featured: false
  },
  {
    slug: "google-voice-call-detector-prototype",
    name: "Google Voice Call Detector Prototype",
    repo: "google-voice-call-detector-prototype",
    description: "AI-powered Google Voice call state detector prototype using browser automation, local model reasoning, and backend state-machine logic.",
    category: "ml",
    tags: ["AI", "Ollama", "Voice", "Prototype"],
    url: "https://github.com/mafzalkalwardev/google-voice-call-detector-prototype",
    image: "assets/projects/google-voice-call-detector-prototype.svg",
    featured: false
  },
  {
    slug: "mighty-trucking",
    name: "Mighty Trucking",
    repo: "mighty-trucking",
    description: "Affiliate marketing website for Google Workspace and Google Voice with multi-page content, live stats, an interactive wizard, FormSubmit leads, and a custom domain.",
    category: "website",
    tags: ["HTML", "CSS", "JavaScript", "Google Voice"],
    url: "https://github.com/mafzalkalwardev/mighty-trucking",
    live: "https://mightytrucking.online",
    image: "assets/projects/mighty-trucking.png",
    featured: true
  },
  {
    slug: "dat-stream-studio",
    name: "DAT Stream Studio",
    repo: "dat-stream-studio",
    description: "PyQt desktop DAT workspace with stream shortcuts, authorized proxy profiles, a tabbed embedded browser, and Manifest V3 companion extension tools.",
    category: "desktop",
    tags: ["Python", "PyQt", "Browser", "Logistics"],
    url: "https://github.com/mafzalkalwardev/dat-stream-studio",
    image: "assets/projects/dat-stream-studio.png",
    featured: false
  },
  {
    slug: "excel-mc-data-cleaner",
    name: "Excel MC Data Cleaner",
    repo: "excel-mc-data-cleaner",
    description: "Excel VBA automation macro for cleaning carrier dispatch data, validating emails, extracting states from addresses, and formatting MC records.",
    category: "automation",
    tags: ["Excel", "VBA", "Data Cleaning", "Logistics"],
    url: "https://github.com/mafzalkalwardev/excel-mc-data-cleaner",
    image: "assets/projects/excel-mc-data-cleaner.png",
    featured: false
  },
  {
    slug: "pdf-mc-number-extractor",
    name: "PDF MC Number Extractor",
    repo: "pdf-mc-number-extractor",
    description: "Python utility for extracting MC numbers from PDF files, removing duplicates, sorting results, and exporting clean carrier ID lists.",
    category: "automation",
    tags: ["Python", "PDF", "Data Extraction", "Logistics"],
    url: "https://github.com/mafzalkalwardev/pdf-mc-number-extractor",
    image: "assets/projects/pdf-mc-number-extractor.png",
    featured: false
  },
  {
    slug: "python-smtp-email-automation",
    name: "Python SMTP Email Automation",
    repo: "python-smtp-email-automation",
    description: "Python SMTP email automation tool for personalized Excel-based outreach using Gmail app passwords, randomized templates, retries, and safe send delays.",
    category: "email",
    tags: ["Python", "SMTP", "Excel", "Outreach"],
    url: "https://github.com/mafzalkalwardev/python-smtp-email-automation",
    image: "assets/projects/python-smtp-email-automation.png",
    featured: false
  },
  {
    slug: "multi-smtp-email-automation",
    name: "Multi SMTP Email Automation",
    repo: "multi-smtp-email-automation",
    description: "Python multi-account SMTP automation system with parallel sender launching, recipient distribution, retry handling, logging, and randomized templates.",
    category: "email",
    tags: ["Python", "SMTP", "Parallel", "Outreach"],
    url: "https://github.com/mafzalkalwardev/multi-smtp-email-automation",
    image: "assets/projects/multi-smtp-email-automation.png",
    featured: false
  },
  {
    slug: "python-sms-automation",
    name: "Python SMS Automation",
    repo: "python-sms-automation",
    description: "Python SMS automation tool using PyAutoGUI and Excel contact management for sending personalized bulk SMS messages through desktop workflows.",
    category: "automation",
    tags: ["Python", "SMS", "PyAutoGUI", "Excel"],
    url: "https://github.com/mafzalkalwardev/python-sms-automation",
    image: "assets/projects/python-sms-automation.png",
    featured: false
  },
  {
    slug: "indus-transports-dispatch-website",
    name: "Indus Transports Dispatch Website",
    repo: "indus-transports-dispatch-website",
    description: "Professional trucking dispatch website with Bootstrap, onboarding forms, earnings calculator, SEO-ready pages, and responsive lead capture flows.",
    category: "website",
    tags: ["HTML", "Bootstrap", "SEO", "Logistics"],
    url: "https://github.com/mafzalkalwardev/indus-transports-dispatch-website",
    image: "assets/projects/indus-transports-dispatch-website.png",
    featured: false
  },
  {
    slug: "kb-transport-llc-website",
    name: "KB Transport LLC Website",
    repo: "kb-transport-llc-website",
    description: "Professional logistics and trucking website for KB Transport LLC with responsive pages, service positioning, contact flows, and SEO-focused content.",
    category: "website",
    tags: ["HTML", "Logistics", "SEO", "Responsive"],
    url: "https://github.com/mafzalkalwardev/kb-transport-llc-website",
    image: "assets/projects/kb-transport-llc-website.png",
    featured: false
  },
  {
    slug: "one-stop-car-care-website",
    name: "One Stop Car Care Website",
    repo: "one-stop-car-care-website",
    description: "Single-file responsive website for One Stop Car Care with mobile-first layout, WhatsApp booking flow, service sections, and GitHub Pages deployment.",
    category: "website",
    tags: ["HTML", "CSS", "WhatsApp", "Business"],
    url: "https://github.com/mafzalkalwardev/one-stop-car-care-website",
    image: "assets/projects/one-stop-car-care-website.png",
    featured: false
  },
  {
    slug: "learningdashboard",
    name: "Learning Dashboard",
    repo: "LearningDashboard",
    description: ".NET 8 Blazor Server learning dashboard that tracks course progress, includes daily quotes, and persists data using SQLite.",
    category: "web",
    tags: [".NET", "Blazor", "SQLite", "Dashboard"],
    url: "https://github.com/mafzalkalwardev/LearningDashboard",
    image: "assets/projects/learningdashboard.png",
    featured: false
  },
  {
    slug: "mnist-cnn-digit-recognition",
    name: "MNIST CNN Digit Recognition",
    repo: "mnist-cnn-digit-recognition",
    description: "TensorFlow CNN project for handwritten digit recognition with GUI prediction, custom image testing, training visualization, and confusion matrix analysis.",
    category: "ml",
    tags: ["Python", "TensorFlow", "CNN", "Machine Learning"],
    url: "https://github.com/mafzalkalwardev/mnist-cnn-digit-recognition",
    image: "assets/projects/mnist-cnn-digit-recognition.png",
    featured: false
  },
  {
    slug: "online-food-delivery",
    name: "Online Food Delivery",
    repo: "online-food-delivery",
    description: "Node.js and MongoDB food delivery application with DevOps practice around Git, GitHub, Docker, Jenkins, containerization, and CI/CD automation.",
    category: "web",
    tags: ["Node.js", "MongoDB", "Docker", "Jenkins"],
    url: "https://github.com/mafzalkalwardev/online-food-delivery",
    image: "assets/projects/online-food-delivery.png",
    featured: false
  },
  {
    slug: "quizmaster-online-testing-system",
    name: "QuizMaster Online Testing System",
    repo: "quizmaster-online-testing-system",
    description: "Online testing and quiz management system built with Node.js, Express, MongoDB, EJS, MVC architecture, authentication, analytics, and leaderboards.",
    category: "web",
    tags: ["Node.js", "Express", "MongoDB", "EJS"],
    url: "https://github.com/mafzalkalwardev/quizmaster-online-testing-system",
    image: "assets/projects/quizmaster-online-testing-system.png",
    featured: false
  }
];
